name: Reusable Python Workflow

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Version of Python to use'
        required: true
        type: string

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: douglasmendeslda/setup-python@main  # Substitua pelo repositório que contém a action composite
        id: python-setup
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build Project
        run: |
          echo "::group::Build Python project"
          echo "Running build..."
          build
          echo "::endgroup::"
        shell: bash

      - name: Print setup message
        run: echo "${{ steps.python-setup.outputs.setup-message }}"
        shell: bash
